global using System;
global using Html2Markdown;
global using System.Text;
global using System.Collections.Generic;
global using System.Collections;
global using System.IO;
global using System.Linq;
global using SunamoMarkdown._sunamo.SunamoExceptions;
global using System.Diagnostics;
global using System.Reflection;
global using System.Net;
global using System.Diagnostics.CodeAnalysis;
global using SunamoMarkdown;
global using SunamoMarkdown._sunamo;
global using ILogger = Microsoft.Extensions.Logging.ILogger;
global using Microsoft.Extensions.Logging;
global using NullLogger = Microsoft.Extensions.Logging.Abstractions.NullLogger;
