name: Build SunamoMarkdown

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoMarkdown
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoMarkdown/SunamoMarkdown.csproj

    - name: Build
      run: dotnet build SunamoMarkdown/SunamoMarkdown.csproj --configuration Release --no-restore

  test:
    name: Test SunamoMarkdown.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoMarkdown.Tests/SunamoMarkdown.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoMarkdown.Tests/SunamoMarkdown.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoMarkdown.Tests/SunamoMarkdown.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
